### PR TITLE
Treat tunnel as established if contains REKEYED

### LINKED ISSUE #33: I suspect ipsec value of REKEYED results in non-zero status from ipsec_exporter
Thanks for a really useful tool! We've been using it for about a year.

We're intermittently getting alerts about tunnels being down when they're up and working.

I suspect ipsec value of REKEYED results in non-zero status from ipsec_exporter

```
$ ipsec status | grep expires
       aaa{56474}:  REKEYED, TUNNEL, reqid 2, expires in 110 seconds
  aaa-ilo{56476}:  REKEYED, TUNNEL, reqid 6, expires in 3 minutes
```
https://github.com/dennisstritzke/ipsec_exporter/blob/9f6164f458358420a6cd41766eadd6f9df4aa17b/ipsec/status.go#L82-L83

### PR DESCRIPTION
**Pull request by mike-sixd**
We're getting alerts for a short periods when output
of strongswan shows REKEYED instead of INSTALLED.

Fixes #33

### CODE REVIEW

**Comment by dennisstritzke** [comment]
Thank you for this improvement! Could you please remove the ipsec_exporter binary from your commit?

**Comment by dennisstritzke** [comment]
I just realised that this change fails the test `TestStatus_connectionUpTunnelMissing`. This test assumes that the tunnel is in state established not installed, if REKEYED is contained in the statement.

We want the status to be `tunnelInstalled`, if REKEYED is contained, right? I have no tunnel at hand to verify my assumption. If so, could you please change that test or allow me to make changes to that branch?

**Comment by mike-sixd** [comment]
I believe you're right.

I've removed the binary and updated the test.

Noticed a warning in test:
```
$ go test
WARN[0000] Unable to retrieve the status of tunnel 'foo'. Reason: doesn't matter  source="status.go:60"
PASS
ok  	github.com/dennisstritzke/ipsec_exporter/ipsec	0.004s
```

**Comment by mike-sixd** [comment]
Also added REKEYING as that was causing non-zero status despite tunnel being up.

**Comment by dennisstritzke** [comment]
The change is included in the [v0.4.0 release](https://github.com/dennisstritzke/ipsec_exporter/releases/tag/v0.4.0). @mike-sixd, thank you for your contribution!

**Pull request merged**
